version: '3.8'

services:
  web:
    image: shaony00/chatjaipt:latest
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlsrv://sa:Not24get@db:1433/ChatJaiPT

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sql2022_
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data: