App\Entity\Message:
  properties:
    body:
      - NotBlank:
          message: "Le message ne peut pas être vide"
      - Length:
          min: 8
          max: 512
          minMessage: "Votre message doit faire au moins {{ limit }} caractères"
          maxMessage: "Votre message doit faire au plus {{ limit }} caractères"

App\Entity\User:
  properties:
    email:
      - Email:
          message: "le champ Email {{ value }} n'est pas valide"
      - NotBlank:
          message: "le champ Email ne peut pas être vide"
    nickname:
      - Length:
          min: 3
          minMessage: "le champ Nom {{ value }} est trop court"
      - NotBlank:
          message: "le champ Nom ne peut pas être vide"
    password:
      - Length:
          min: 8
          minMessage: "Votre mot de passe doit faire au moins {{ limit }} caractères"
      - NotBlank:
          message: "Le mot de passe ne peut pas être vide"