App\DTO\MessageDto:
  properties:
    body:
      - NotBlank:
          message: "Le message ne peut pas être vide"
      - Length:
          min: 8
          max: 512
          minMessage: "Votre message doit faire au moins {{ limit }} caractères"
          maxMessage: "Votre message doit faire au plus {{ limit }} caractères"

App\DTO\Forgot_PasswordDto:
  properties:
    password:
      - Length:
          min: 8
          minMessage: "Votre mot de passe doit faire au moins {{ limit }} caractères"
      - NotBlank:
          message: "Le mot de passe ne peut pas être vide"
    confirm_password:
        - Length:
            min: 8
            minMessage: "Votre mot de passe doit faire au moins {{ limit }} caractères"
        - NotBlank:
            message: "Le mot de passe ne peut pas être vide"
        - Expression:
            expression: "this.getPassword() === this.getConfirmPassword()"
            message: "Les mots de passe ne correspondent pas"

App\DTO\EmailDTO:
  properties:
    email:
      - Email:
          message: "le champ Email {{ value }} n'est pas valide"
      - NotBlank:
          message: "le champ Email ne peut pas être vide"